# Setup
title:        사과농축액
tagline:      지금 바로 시작
baseurl:      ""
paginate:     1
locale:       "ko"

# About/contact
author:
  name:       idas4you
  url:        https://idas4you.github.io/
  contact:    idas4you@gmail.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown